<a href="https://colab.research.google.com/github/PRAN20/LeafSnap-Model_1/blob/main/AlexNet_m1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Calculating Accuracy by Using Different Classification**

# **Importing Header Files**

In [ ]:
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
import os

# **Importing DataSet**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#os.makedirs('dataset')

In [ ]:
!unzip "/content/drive/MyDrive/LeafSnap-1.zip" -d "dataset"

Archive:  /content/drive/MyDrive/LeafSnap-1.zip
 extracting: dataset/content/LeafSnap-1 Csv/X_test.csv  
 extracting: dataset/content/LeafSnap-1 Csv/y_train.csv  
 extracting: dataset/content/LeafSnap-1 Csv/y_test.csv  
 extracting: dataset/content/LeafSnap-1 Csv/X_train.csv  


In [ ]:
import pandas as pd
train_images=pd.read_csv("/content/dataset/content/LeafSnap-1 Csv/X_train.csv",header=None)
x_train=train_images.iloc[:,:].values
x_train.shape

(6109, 1000)

In [ ]:
train_labels=pd.read_csv("/content/dataset/content/LeafSnap-1 Csv/y_train.csv",header=None)
y_train=train_labels.iloc[:,:].values
y_train= y_train.flatten()
y_train.shape

(6109,)

In [ ]:
import pandas as pd
test_images=pd.read_csv("/content/dataset/content/LeafSnap-1 Csv/X_test.csv",header=None)
x_test=test_images.iloc[:,:].values
x_test.shape

(917, 1000)

In [ ]:
test_labels=pd.read_csv("/content/dataset/content/LeafSnap-1 Csv/y_test.csv",header=None)
y_test=test_labels.iloc[:,:].values
y_test= y_test.flatten()
y_test.shape

(917,)

# **Determing The Shape of all The Data**

In [ ]:
x_train.shape

(6109, 1000)

In [ ]:
y_train.shape

(6109,)

In [ ]:
x_test.shape

(917, 1000)

In [ ]:
y_test.shape

(917,)

# **Training The MLP Model**

In [ ]:
from sklearn.neural_network import MLPClassifier
classifier = MLPClassifier(max_iter = 500, activation = 'relu')
classifier.fit(x_train, y_train)

MLPClassifier(max_iter=500)

**Testing the Model**

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
print(y_pred)
y_pred.shape

['quercus_acutissima' 'quercus_acutissima' 'quercus_acutissima'
 'quercus_acutissima' 'quercus_acutissima' 'quercus_acutissima'
 'pinus_rigida' 'pinus_nigra' 'pinus_nigra' 'pinus_rigida' 'pinus_rigida'
 'magnolia_macrophylla' 'prunus_serotina' 'styrax_japonica'
 'pinus_bungeana' 'pinus_bungeana' 'pinus_bungeana' 'pinus_bungeana'
 'pinus_bungeana' 'pinus_bungeana' 'aesculus_flava' 'carya_cordiformis'
 'salix_matsudana' 'salix_matsudana' 'salix_matsudana' 'salix_matsudana'
 'quercus_phellos' 'pinus_peucea' 'pinus_peucea' 'pinus_peucea'
 'pinus_peucea' 'pinus_bungeana' 'platanus_acerifolia' 'betula_nigra'
 'cercis_canadensis' 'cornus_kousa' 'aesculus_glabra' 'carya_cordiformis'
 'carya_cordiformis' 'carya_cordiformis' 'carya_cordiformis'
 'quercus_rubra' 'pyrus_calleryana' 'pyrus_calleryana' 'pyrus_calleryana'
 'pyrus_calleryana' 'pyrus_calleryana' 'pyrus_calleryana'
 'styrax_japonica' 'magnolia_soulangiana' 'magnolia_stellata'
 'carya_glabra' 'carya_glabra' 'carya_glabra' 'carya_glabra'


(917,)

**Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 6,  0,  0, ...,  0,  0,  0],
       [ 0,  3,  0, ...,  0,  0,  0],
       [ 0,  0,  5, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 15,  0,  0],
       [ 0,  0,  0, ...,  0,  5,  0],
       [ 0,  0,  0, ...,  0,  0,  6]])

**Calculating the Accuracy of the Model**

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                              precision    recall  f1-score   support

              abies_concolor       1.00      1.00      1.00         6
          abies_nordmanniana       0.60      0.75      0.67         4
              acer_campestre       0.62      1.00      0.77         5
                acer_ginnala       1.00      0.50      0.67         4
                acer_griseum       0.83      0.83      0.83         6
                acer_negundo       0.43      0.75      0.55         4
               acer_palmatum       0.64      0.90      0.75        10
          acer_pensylvanicum       0.43      0.75      0.55         4
            acer_platanoides       1.00      0.50      0.67         2
         acer_pseudoplatanus       0.00      0.00      0.00         2
                 acer_rubrum       0.50      0.40      0.44         5
            acer_saccharinum       1.00      1.00      1.00         5
              acer_saccharum       1.00      0.33      0.50         3
              aescu

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import accuracy_score
mlp = accuracy_score(y_test, y_pred)
mlp

0.6717557251908397

# **Naive-Bays Model**

In [ ]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = clf.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
naive = accuracy_score(y_test, y_pred)
naive

[[ 4  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  0  3 ...  0  0  0]
 ...
 [ 0  0  0 ... 10  0  0]
 [ 0  0  0 ...  0  2  0]
 [ 0  0  0 ...  0  0  2]]


0.4143947655398037

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                              precision    recall  f1-score   support

              abies_concolor       1.00      0.67      0.80         6
          abies_nordmanniana       1.00      0.25      0.40         4
              acer_campestre       0.50      0.60      0.55         5
                acer_ginnala       0.60      0.75      0.67         4
                acer_griseum       0.00      0.00      0.00         6
                acer_negundo       0.40      0.50      0.44         4
               acer_palmatum       0.07      0.10      0.08        10
          acer_pensylvanicum       0.25      0.50      0.33         4
            acer_platanoides       1.00      1.00      1.00         2
         acer_pseudoplatanus       1.00      0.50      0.67         2
                 acer_rubrum       0.17      0.40      0.24         5
            acer_saccharinum       0.50      0.80      0.62         5
              acer_saccharum       0.00      0.00      0.00         3
              aescu

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Random Forest Classification**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(n_estimators = 70, oob_score = True, n_jobs = -1,max_features = None, min_samples_leaf = 30)
clf1.fit(x_train, y_train)

RandomForestClassifier(max_features=None, min_samples_leaf=30, n_estimators=70,
                       n_jobs=-1, oob_score=True)

In [ ]:
y_pred = clf1.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
rand = accuracy_score(y_test, y_pred)
rand

[[ 6  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  0  3 ...  0  0  0]
 ...
 [ 0  0  0 ... 13  0  0]
 [ 0  0  0 ...  1  1  0]
 [ 0  0  0 ...  0  0  1]]


0.4776444929116685

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                              precision    recall  f1-score   support

              abies_concolor       0.75      1.00      0.86         6
          abies_nordmanniana       0.50      0.25      0.33         4
              acer_campestre       0.60      0.60      0.60         5
                acer_ginnala       1.00      0.25      0.40         4
                acer_griseum       0.50      0.17      0.25         6
                acer_negundo       0.00      0.00      0.00         4
               acer_palmatum       0.26      0.80      0.39        10
          acer_pensylvanicum       0.40      0.50      0.44         4
            acer_platanoides       0.00      0.00      0.00         2
         acer_pseudoplatanus       0.00      0.00      0.00         2
                 acer_rubrum       0.38      0.60      0.46         5
            acer_saccharinum       1.00      0.20      0.33         5
              acer_saccharum       0.38      1.00      0.55         3
              aescu

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **K-NN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
kn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [ ]:
y_pred = kn.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
knn = accuracy_score(y_test, y_pred)
knn

[[ 6  0  0 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]
 [ 0  0  5 ...  0  0  0]
 ...
 [ 0  0  0 ... 14  0  0]
 [ 0  0  0 ...  0  4  0]
 [ 0  0  0 ...  0  0  2]]


0.5605234460196292

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                              precision    recall  f1-score   support

              abies_concolor       0.60      1.00      0.75         6
          abies_nordmanniana       0.67      0.50      0.57         4
              acer_campestre       0.56      1.00      0.71         5
                acer_ginnala       0.67      0.50      0.57         4
                acer_griseum       0.75      0.50      0.60         6
                acer_negundo       1.00      0.50      0.67         4
               acer_palmatum       0.43      1.00      0.61        10
          acer_pensylvanicum       0.40      0.50      0.44         4
            acer_platanoides       0.00      0.00      0.00         2
         acer_pseudoplatanus       0.20      0.50      0.29         2
                 acer_rubrum       0.33      0.60      0.43         5
            acer_saccharinum       1.00      1.00      1.00         5
              acer_saccharum       0.50      0.33      0.40         3
              aescu

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf2 = DecisionTreeClassifier(max_depth = 10, random_state = 101, max_features = None, min_samples_leaf = 15)
clf2.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=15, random_state=101)

In [ ]:
y_pred = clf2.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
desc = accuracy_score(y_test, y_pred)
desc

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 9 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.23991275899672845

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                              precision    recall  f1-score   support

              abies_concolor       0.33      0.17      0.22         6
          abies_nordmanniana       0.00      0.00      0.00         4
              acer_campestre       0.00      0.00      0.00         5
                acer_ginnala       0.00      0.00      0.00         4
                acer_griseum       0.00      0.00      0.00         6
                acer_negundo       0.00      0.00      0.00         4
               acer_palmatum       0.24      0.80      0.37        10
          acer_pensylvanicum       0.00      0.00      0.00         4
            acer_platanoides       0.00      0.00      0.00         2
         acer_pseudoplatanus       0.00      0.00      0.00         2
                 acer_rubrum       0.00      0.00      0.00         5
            acer_saccharinum       0.00      0.00      0.00         5
              acer_saccharum       0.00      0.00      0.00         3
              aescu

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Kernel SVM**

In [ ]:
from sklearn.svm import SVC
classifier1 = SVC(kernel = 'linear', C =  1,  random_state = 101)
classifier1.fit(x_train, y_train)

SVC(C=1, kernel='linear', random_state=101)

In [ ]:
y_pred = classifier1.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svm = accuracy_score(y_test, y_pred)
svm

[[ 6  0  0 ...  0  0  0]
 [ 0  4  0 ...  0  0  0]
 [ 0  0  5 ...  0  0  0]
 ...
 [ 0  0  0 ... 15  0  0]
 [ 0  0  0 ...  0  4  0]
 [ 0  0  0 ...  0  0  6]]


0.7175572519083969

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                              precision    recall  f1-score   support

              abies_concolor       1.00      1.00      1.00         6
          abies_nordmanniana       0.80      1.00      0.89         4
              acer_campestre       0.71      1.00      0.83         5
                acer_ginnala       0.67      0.50      0.57         4
                acer_griseum       0.86      1.00      0.92         6
                acer_negundo       0.67      0.50      0.57         4
               acer_palmatum       0.83      1.00      0.91        10
          acer_pensylvanicum       0.50      1.00      0.67         4
            acer_platanoides       1.00      1.00      1.00         2
         acer_pseudoplatanus       1.00      0.50      0.67         2
                 acer_rubrum       0.50      0.60      0.55         5
            acer_saccharinum       1.00      1.00      1.00         5
              acer_saccharum       1.00      0.67      0.80         3
              aescu

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Linear SVC**

In [ ]:
from sklearn.svm import LinearSVC
class3 = LinearSVC(random_state=0, tol=1e-5)
class3.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC(random_state=0, tol=1e-05)

In [ ]:
y_pred = class3.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svc = accuracy_score(y_test, y_pred)
svc

[[ 6  0  0 ...  0  0  0]
 [ 0  3  0 ...  0  0  0]
 [ 0  0  5 ...  0  0  0]
 ...
 [ 0  0  0 ... 15  0  0]
 [ 0  0  0 ...  0  5  0]
 [ 0  0  0 ...  0  0  6]]


0.7404580152671756

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                              precision    recall  f1-score   support

              abies_concolor       1.00      1.00      1.00         6
          abies_nordmanniana       0.75      0.75      0.75         4
              acer_campestre       0.83      1.00      0.91         5
                acer_ginnala       0.50      0.75      0.60         4
                acer_griseum       1.00      0.83      0.91         6
                acer_negundo       0.67      0.50      0.57         4
               acer_palmatum       0.83      1.00      0.91        10
          acer_pensylvanicum       0.57      1.00      0.73         4
            acer_platanoides       1.00      1.00      1.00         2
         acer_pseudoplatanus       1.00      0.50      0.67         2
                 acer_rubrum       0.67      0.80      0.73         5
            acer_saccharinum       1.00      1.00      1.00         5
              acer_saccharum       1.00      0.67      0.80         3
              aescu

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier4 = LogisticRegression(random_state = 0)
classifier4.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier4.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
logis = accuracy_score(y_test, y_pred)
logis

[[ 6  0  0 ...  0  0  0]
 [ 0  3  0 ...  0  0  0]
 [ 0  0  4 ...  0  0  0]
 ...
 [ 0  0  0 ... 15  0  0]
 [ 0  0  0 ...  0  6  0]
 [ 0  0  0 ...  0  0  5]]


0.7142857142857143

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                              precision    recall  f1-score   support

              abies_concolor       1.00      1.00      1.00         6
          abies_nordmanniana       0.60      0.75      0.67         4
              acer_campestre       0.80      0.80      0.80         5
                acer_ginnala       0.57      1.00      0.73         4
                acer_griseum       0.71      0.83      0.77         6
                acer_negundo       1.00      0.50      0.67         4
               acer_palmatum       0.71      1.00      0.83        10
          acer_pensylvanicum       0.50      1.00      0.67         4
            acer_platanoides       0.67      1.00      0.80         2
         acer_pseudoplatanus       1.00      0.50      0.67         2
                 acer_rubrum       0.80      0.80      0.80         5
            acer_saccharinum       1.00      1.00      1.00         5
              acer_saccharum       1.00      0.33      0.50         3
              aescu

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Stochastic Gradient Descent**

In [ ]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss = 'modified_huber', shuffle = True, random_state = 101)
sgd.fit(x_train, y_train)

SGDClassifier(loss='modified_huber', random_state=101)

In [ ]:
y_pred = sgd.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
stoc = accuracy_score(y_test, y_pred)
stoc

[[ 6  0  0 ...  0  0  0]
 [ 0  3  0 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ... 14  0  0]
 [ 0  0  0 ...  0  4  1]
 [ 0  0  0 ...  0  0  6]]


0.6412213740458015

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                              precision    recall  f1-score   support

              abies_concolor       1.00      1.00      1.00         6
          abies_nordmanniana       0.75      0.75      0.75         4
              acer_campestre       0.50      0.20      0.29         5
                acer_ginnala       0.00      0.00      0.00         4
                acer_griseum       1.00      0.17      0.29         6
                acer_negundo       0.00      0.00      0.00         4
               acer_palmatum       0.62      1.00      0.77        10
          acer_pensylvanicum       0.60      0.75      0.67         4
            acer_platanoides       0.00      0.00      0.00         2
         acer_pseudoplatanus       0.00      0.00      0.00         2
                 acer_rubrum       1.00      0.40      0.57         5
            acer_saccharinum       1.00      1.00      1.00         5
              acer_saccharum       1.00      0.33      0.50         3
              aescu

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Final Results**

In [ ]:
print('Accuracy of MLP Model is {}'.format(mlp))
print('Accuracy of Naive-Bays Model is {}'.format(naive))
print('Accuracy of Random Forest Model is {}'.format(rand))
print('Accuracy of K-NN Model is {}'.format(knn))
print('Accuracy of Decision Tree Model is {}'.format(desc))
print('Accuracy of Kernel Svm Model is {}'.format(svm))
print('Accuracy of Linear SVC Model is {}'.format(svc))
print('Accuracy of Logistic Regression Model is {}'.format(logis))
print('Accuracy of Stochastic Gradient Descent Model is {}'.format(stoc))

Accuracy of MLP Model is 0.6717557251908397
Accuracy of Naive-Bays Model is 0.4143947655398037
Accuracy of Random Forest Model is 0.4776444929116685
Accuracy of K-NN Model is 0.5605234460196292
Accuracy of Decision Tree Model is 0.23991275899672845
Accuracy of Kernel Svm Model is 0.7175572519083969
Accuracy of Linear SVC Model is 0.7404580152671756
Accuracy of Logistic Regression Model is 0.7142857142857143
Accuracy of Stochastic Gradient Descent Model is 0.6412213740458015


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x_train[:, 2] = le.fit_transform(x_train[:,2])

In [ ]:
import tensorflow as tf

an = tf.keras.models.Sequential()
an.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [ ]:
an.layers

In [ ]:
an.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
an.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


UnimplementedError: ignored